version: "3"
services:

  itmanager:
    image: api-itmanager:latest
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:11
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=itmanagerdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432